name: dat158
dependencies:
- python >= 3.8.0
- pip
- pytest
- flask
- flask-wtf
- conda-forge::flask-bootstrap
- ipython
- ipykernel
- ipywidgets
- jupyter
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- git
- numpy
- matplotlib
- pandas
- scikit-learn-intelex
- scipy
- seaborn
- conda-forge::category_encoders
- conda-forge::shap
- hyperopt
- xgboost
- pip:
  - pip >= 19.0
  - kaggle
  - pandas-profiling
  - xlrd
  - eli5
  - pdpbox
  - nbdime
  - python-dotenv
 # - pycaret
  - gunicorn
  
